
platform :ios, '11.0'

target 'FXVideoEdit' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Masonry'
  pod 'YYKit'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MyLayout'
  pod 'QMUIKit'
  pod 'YogaKit'
end


post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
        end
    end
end
